### ISSUE TITLE
Buttons in Fullscreen mode

### ISSUE THREAD

**Issue by Hofyyy** [IPCams/BugTracker#1]
**Is your feature request related to a problem? Please describe.**
Buttons in fullscreen mode on ios visible all the time.

**Describe the solution you'd like**
Hide close and pause button after 10 seconds and show again after one sceen touch for 10 sec.

**Comment by tylerjonesio** [comment]
Thanks for the feature request! I have some enhancements for auto hiding/showing playback controls planned.

**Comment by harrynrobinson** [comment]
Tyler - thanks so much for updating your app. My wife and I use it all day every day to monitor our new born across our different devices. The recent updates have been great. I second this request here about hiding the control buttons.

**Comment by PocketTim** [comment]
Another person here chiming in on the controls being hide-able. 

Otherwise. Fantastic app.

**Comment by tylerjonesio** [comment]
Version 2.0 has rolled out and includes some improvements for full screen mode, including auto hiding the controls. If you all run into any issues with this please file a bug report. Otherwise, hopefully this should be a big improvement!
