### ISSUE TITLE
Video Stretching

### ISSUE THREAD

**Issue by aleczdr** [IPCams/BugTracker#10]
**Is your feature request related to a problem? Please describe**
I have some cameras that use non-square pixels in their streams, so they appear narrower in the app.

There could be an option that would allow the image’s aspect ratio to be changed.

**Additional context**
The camera’s output resolution is 720x480 but the stream should be 853x480 on screen

**Comment by tylerjonesio** [comment]
Thanks for the request! I think something like this should be doable. What kind of streams do your cameras use? (MJPEG, RTSP, H264)?

**Comment by aleczdr** [comment]
Rtsp

**Comment by tylerjonesio** [comment]
Good news! Version 2.0 has rolled out and includes an option to set a custom aspect override for rtsp streams. If you edit your camera you can add the desired ratio override under the 'Custom Aspect' setting. If you run into any issues with this, please feel free to file a bug report.
