### ISSUE TITLE
Add url scheme with "?"

### ISSUE THREAD

**Issue by BullzLabz** [IPCams/BugTracker#15]
Hello, 

My cams run with rstp feed but the url scheme is like this:

- rtsp://my_ip_address:554/user=admin&password=&channel=1&stream=0.sdp?

I tried to put this url scheme in IPCams but each time the last "?" symbol seems to be removed from the url scheme! 

Could you add the possibility to add this "?" symbol please.

**Comment by fmarcoux96** [comment]
Why is it needed? It's normally at the beginning, like `...:554/?user=admin...`.

**Comment by BullzLabz** [comment]
I've no idea, I'm not the one who manufactured this ip camera, you would have to ask the manufacturer, but it's a good question!
I also find it weird !!!

IP Camera model : Digoo M1Q

**Comment by fmarcoux96** [comment]
According to this : https://github.com/yuvadm/DG-M1Q

You need to use `rtsp://admin:password@IP_ADDRESS/onvif1`

**Comment by BullzLabz** [comment]
I'll try that, thanks for your help

**Comment by tylerjonesio** [comment]
As mentioned the `?` is usually used at the start a query string, not at the end. Having it at the end isn't really part of the URL standard, which is probably why it is getting it stripped out here. This wouldn't be the first time I've seen a manufacture use something nonstandard though. Hopefully the alternate stream url fmarcoux96 provided works for your camera. 

If it is truly needed though and there isn't an alternate stream url that works, I can attempt to look into seeing what I can do to preserve the trailing ?, but I can't really promise anything.
