### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by Jatwsp420** [IPCams/BugTracker#17]
Can somebody please help me figure out how to get my camera as online. I have read and tried everything. I just don’t have it. Frustrated isn’t the word. I can pull them up on some other programs. But not this one. Any help would be greatly appreciated. They are sercomm icamera 2. I can do it wireless or Ethernet. Thanks in advance.

**Comment by tylerjonesio** [comment]
After a [quick search](https://www.google.com/search?q=sercomm+icamera2+camera+url), it looks like multiple sources show your camera should support a RTSP or MJPEG stream. If you add your camera with its IP address and one of the following stream settings, you should be able to connect. 

_Note: If your camera requires a username/password. You can toggle on and enable the `HTTP Auth` option to provide a username and password._

### RTSP Stream
Type: `RTSP`
URL Scheme: `rtsp`
Host/IP: `(Your camera's IP address)`
Port: `554`
Path: `img/video.sav`
### MJPEG Stream
Type: `MJPEG`
URL Scheme: `http`
Host/IP: `(Your camera's IP address)`
Port: `80`
Path: `img/mjpeg.jpg`

Hopefully one of these options will work to connect your camera!
