### ISSUE TITLE
Audio unmutes when exiting camera view and then re entering camera view

### ISSUE THREAD

**Issue by hugoender** [IPCams/BugTracker#19]
**Describe the bug**
Muting camera audio does not stick. 

**To Reproduce**
Enter camera view of one camera. The audio will automatically be unmuted. Press mute button. Exit camera view and then enter camera view again and the audio will be unmuted. 

**Expected behavior**
If you mute the camera audio it should remain muted. 

**Screenshots**

**App Version**
Latest version. 

**Device & OS Version**
Any iOS device or version. 

**Additional context**

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.1 is currently in the process of rolling out and includes a fix for persisting the mute state between camera views and app sessions. Hopefully this fixes your issue, but if not just let me know.
