### ISSUE TITLE
Enlarge space for camera previews in fullscreen mode

### ISSUE THREAD

**Issue by pfluger42** [IPCams/BugTracker#20]
The app currently keeps the rounded corner video previews when going into fullscreen mode. 

I think it might make sense to enlarge the videos in fullscreen to use as much screen real estate as possible. That means remove all padding and margins as well as the rounded corners.

**Comment by CloudCray** [comment]
+1 to this. Additionally, it would be nice if videos could be dragged if they are cropped or zoomed

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.1 is currently in the process of rolling out and includes an option to enable this behavior. If you go and edit your dashboard, there is now an `Expanded Grid` option that removes the padding and corners for a more expanded look.

@CloudCray, I've messed around in the past with adding the ability to zoom and drag (for zoomed/cropped cameras) in the dashboard view but that presented some issues. I'll keep the request in mind though for the future to see if there is anything to be done there.
