### ISSUE TITLE
Zooming/scrolling camera image feels wrong

### ISSUE THREAD

**Issue by pfluger42** [IPCams/BugTracker#21]
When viewing a camera the zooming/scrolling feels wrong. When zoomed in a little bit I can move the picture around and even out of screen. Also when pinching out a bit the image doesn't stay centered. I am not sure if that is intended?

I was struggling with zooming/scrolling images in an app in the past, too. Here is some sample code. Maybe that helps.

    import UIKit

    class PhotoViewController: UIViewController, UIScrollViewDelegate {

    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var imageView: UIImageView!  // embedded in scrollView
    
    @IBOutlet weak var imageViewConstraintLeft: NSLayoutConstraint!   // space to left between scrollview and imageview
    @IBOutlet weak var imageViewConstraintRight: NSLayoutConstraint!  // space to right between scrollview and imageview
    @IBOutlet weak var imageViewConstraintBottom: NSLayoutConstraint!  // space to bottom between scrollview and imageview
    @IBOutlet weak var imageViewConstraintTop: NSLayoutConstraint!  // space to top between scrollview and imageview
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // TODO: loading the image into the imageview here
        // ...

        // adjust scroll rate
        scrollView.decelerationRate = UIScrollView.DecelerationRate.fast
        
        // listen for double taps
        let doubleTapGesture = UITapGestureRecognizer(target: self, action: #selector(self.handleDoubleTap(_:)))
        doubleTapGesture.numberOfTapsRequired = 2
        view.addGestureRecognizer(doubleTapGesture)

        // listen for single taps
        let singleTapGesture = UITapGestureRecognizer(target: self, action: #selector(self.handleSingleTap(_:)))
        singleTapGesture.require(toFail: doubleTapGesture)
        view.addGestureRecognizer(singleTapGesture)

        updateZoom()
        updateConstraints()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    override func viewDidLayoutSubviews() {
        
        updateZoom()
        updateConstraints()
    }
    
    @objc func handleDoubleTap(_ sender: UITapGestureRecognizer) {
        
        // zoom in/out on double tap
        if scrollView.zoomScale <= scrollView.minimumZoomScale {
            scrollView.setZoomScale(1.0, animated: true)
        } else {
            scrollView.setZoomScale(scrollView.minimumZoomScale, animated: true)
        }
    }

    @objc func handleSingleTap(_ sender: UITapGestureRecognizer) {
        
        // show/hide bars on single tap
        if let photosViewController = self.parent?.parent as? PhotosViewController {
            photosViewController.toggleBars()
        }
    }

    // MARK: - Implementation
    
    func updateZoom() {
        
        guard let image = imageView!.image else {
            return
        }
        
        var minZoom = min(scrollView.bounds.width / image.size.width, scrollView.bounds.height / image.size.height);
        
        if (minZoom > 1.0) {
            minZoom = 1.0;
        }
        
        scrollView.minimumZoomScale = minZoom;
        scrollView.zoomScale = minZoom;
        scrollView.maximumZoomScale = 1.0
    }
    
    func updateConstraints() {
        
        guard let image = imageView!.image else {
            return
        }
        let imageWidth = image.size.width
        let imageHeight = image.size.height
        
        let viewWidth = scrollView.bounds.width
        let viewHeight = scrollView.bounds.height
        
        // center image if it is smaller than the scroll view
        var hPadding = (viewWidth - scrollView.zoomScale * imageWidth) / 2
        if hPadding < 0 { hPadding = 0 }
        
        var vPadding = (viewHeight - scrollView.zoomScale * imageHeight) / 2
        if vPadding < 0 { vPadding = 0 }
        
        imageViewConstraintLeft.constant = hPadding
        imageViewConstraintRight.constant = hPadding
        
        imageViewConstraintTop.constant = vPadding
        imageViewConstraintBottom.constant = vPadding
        
        view.layoutIfNeeded()
    }

    // MARK: - UIScrollViewDelegate
    
    func scrollViewDidZoom(_ scrollView: UIScrollView) {
        updateConstraints()
        
        print("Zoom changed \(scrollView.zoomScale), min is \(scrollView.minimumZoomScale)")
        
        if scrollView.zoomScale > scrollView.minimumZoomScale {
            DispatchQueue.main.async {
                if let photosViewController = self.parent?.parent as? PhotosViewController {
                    photosViewController.hideBars()
                }
            }
        } else {
            DispatchQueue.main.async {
                if let photosViewController = self.parent?.parent as? PhotosViewController {
                    photosViewController.showBars()
                }
            }
        }

    }
    
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return imageView;
    }
    }

**Comment by tylerjonesio** [comment]
Good news! IPCams 2.2 is in the process of rolling out and includes improvements to the camera view with scrolling and zooming. This issue should be fixed now, but please let me know if you run into any more issues with it.
