### ISSUE TITLE
Can't accept third-party cert on https connection and move on to the cam view

### ISSUE THREAD

**Issue by samghubber** [IPCams/BugTracker#25]
An invalid (third-party) cert warning pops up after a cam setup with https url and it's impossible to accept/dismiss that warning. 

Latest app version, ios 13.6, iPhone 6s

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.1 is currently in the process of rolling out and includes the ability to disable ssl verification. In the settings tab there is a new `Disable SSL Verification` toggle that will disable ssl verification and stop these warnings. Feel free to try this out and let me know how it works.
