### ISSUE TITLE
Baby Monitor light for the night

### ISSUE THREAD

**Issue by Hofyyy** [IPCams/BugTracker#3]
**Is your feature request related to a problem? Please describe.**
One to two use cases is that we monitor our baby at night using an rtsp stream from a professional camera.
At the moment we start the IPCam app look to one video (not multiple cams).
Then we lock the iPad, because the display is too bright for the night when we would like to sleep.
If our baby woke up and we can hear noice we unlock the iPad.
Then the video restarts and we can check if the baby can continue alone or we have to go into the room.

**Describe the solution you'd like**
The perfect feature for us would be.
- One timer for auto shutdown the display, or set brightness too zero and show black. (default off)
   In my use case I would set 10 sec.
- One percent slider (0->100%) for loudness trash hold.
   If trash hold is reached display will be reenabled. Then timer got started for e.g. 10 sec. for display off again.
   If baby makes noice, the timer got reset all the time, so display stays bright.
- And maybe a Botton in fullscreen mode, like the close or pause button, which is visible if timer is set, which release enables the mode.  Maybe a Hourglass or a soother ...

 
Then we could let the iPad on and we do not need to touch the iPad in the night ...
  

**Additional context**

**Comment by tylerjonesio** [comment]
Thanks for the feature request! It would be cool to be able to take action here (like adjusting screen brightness) after an event occurred during the stream such as audio or motion. I'll keep this in consideration while planning new features.
