### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by mattbone99** [IPCams/BugTracker#30]
I haven't found a good macOS version of an app like this and would be great to be able to have this on my Mac as well. The app is one of the best viewers I have found and to get this on the Mac would be perfect.

**Comment by tylerjonesio** [comment]
Thanks for the request! A proper macOS version of IPCams is something I'd love to have and think would work well. I don't have a definitive timeline at the moment but it is something I do plan to work on.

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.3 has been released and has a new Mac app counterpart available for machines running Big Sur. Feel free to leave a bug report for any issues that arise or file a feature request for any improvement suggestions.
