### ISSUE TITLE
Allow music app to play in background

### ISSUE THREAD

**Issue by nickmay** [IPCams/BugTracker#32]
I would like an option to be able to open the app and it show me the video streams, but to allow another app to continue to play music / audio in the background. 

**Describe the solution you'd like**
I want to monitor cameras visually, but continue to listen to sound from another app - e.g. a music or radio app. 

Ideally I would have a shortcut option that let me start IPCams in this special mode on a case by case basis.

This would be a good thing to make "Pro version only".

**Comment by nickmay** [comment]
Now possible on 2.2 - thank you!

**Comment by tylerjonesio** [comment]
Good news! IPCams 2.2 is in the process of rolling out which changes the default behavior for audio allowing background playback from other apps to continue. If you run into any issues with this, feel free to leave a bug report.
