### ISSUE TITLE
Disable Screen Time out not working as it should

### ISSUE THREAD

**Issue by mrfatboy** [IPCams/BugTracker#37]
The “Disable Screen Time Out” does not let the iPhone/iPad go to sleep/lock the screen after time (set in iPhone/iPad settings)

It seems to have no affect at all. 

**To Reproduce**
Set the “Disable Screen Time Out” setting to OFF. Live stream a camera. The screen never dims/sleeps/locks even when it is set to in the idevice settings. 

**Expected behavior**
If Disable Screen Time Out is OFF. The screen should dim/sleep/lock after the time that is set in the idevice’s settings. 

**Screenshots**

**App Version**
App version can be found at the bottom of the settings page.

**Device & OS Version**
List device (iPhone/iPad), model (XS, 11 Pro, etc.) and OS version (13.5, 14.0, etc.).

ipad 4 mini 14.4.1
iPhone 11 14.2

**Additional context**

**Comment by nihebe** [comment]
+1, same problem here - I need the iPad Screen to sleep after screen timeout, because I wake it up with push messages in guided access mode.

**Comment by mrfatboy** [comment]
This is my go to app for camera viewing. I hope this bug/feature gets fixed. In the meantime the Owlr camera app has an option to let the iPhone/iPad sleep.

**Comment by nihebe** [comment]
Thanks a lot for sharing - I would also prefer to use this app, but can't do so as long as sleep doesn't work. Going with "MVR" so long...

**Comment by mrfatboy** [comment]
This issue seems to be now fixed in iOS version 2.3

**Comment by tylerjonesio** [comment]
I'm glad to hear it is working for you! The previous screen time out option was originally meant to disable auto lock for certain streams (particularly MJPEG) where the device would sleep automatically, but it was never designed to do the opposite and allow auto lock when playing other stream types. Which admittedly made for a pretty confusing option as IPCams has grown. 

I've migrated this into a newer `Allow Device Auto-Lock` option in 2.3 which now does as expected for all stream types. If enabled it will override the video player sleep functionality and allow your device's auto lock settings to function normally.

**Comment by mrfatboy** [comment]
Fix appreciated👍
