### ISSUE TITLE
Please add “let device sleep option”

### ISSUE THREAD

**Issue by mrfatboy** [IPCams/BugTracker#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I am trying to use ipcams in my HomeKit automations.  When motion is detected I want my iPad mini to wake and display the default camera in full screen. This part is working. 

Then have the iPad go back to sleep based on the time set in the Ipad’s “display settings”

Currently, while the camera is streaming the iPad never goes to sleep (which it should by default). I would like to have an override to let it fall back asleep.  It would be even nicer to have its own sleep timer in the app if possible. 

**Additional context**

**Comment by tylerjonesio** [comment]
This should be fixed alongside #37 with the included enhancements in 2.3.
