### ISSUE TITLE
Launch in full screen

### ISSUE THREAD

**Issue by shinji666** [IPCams/BugTracker#41]
**Is your feature request related to a problem? Please describe.**
Awesome that we now can launch in dashboard, it would be even better if we have the option to open in full screen mode

**Describe the solution you'd like**
Open in full screen mode

**Additional context**

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.3 is in the process of rolling out and includes a new launch shortcut setting to open in fullscreen. Feel free to try it out, and let me know if any issues arise.
