### ISSUE TITLE
Split screen support on the ipad

### ISSUE THREAD

**Issue by jrfcs** [IPCams/BugTracker#44]
Looking for a ipcam viewer that works in split screen on an iPad Pro while another app is running side by side.
Can this app support this? Want to be apple to surf on safari for example on the left side of the screen while ipcam viewer is showing stream on right side window.

**Describe the solution you'd like*

**Comment by tylerjonesio** [comment]
Yep! IPCams supports split screen on iPad. You can use it with any other supported split view app side by side. It also support multiple windows so you can view multiple instances of the app side by side.
