### ISSUE TITLE
App shortcuts does not change camera 

### ISSUE THREAD

**Issue by DeathBlade** [IPCams/BugTracker#5]
If I open a camera with “3D touch” then say go to open another camera a few minutes later it just shows the original camera that was opened. I have to kill the app or wait for the app to close on its own to use another shortcut.

**Comment by tylerjonesio** [comment]
Thanks for the report! I think I've identified the issue and am working on a fix for this.

**Comment by tylerjonesio** [comment]
This should be fixed in version 1.8.2 that was just released.

**Comment by DeathBlade** [comment]
Yep, Just updated and tested it, seems to be working.  Thanks for being on top of the issues.
