### ISSUE TITLE
MacOS version fails to show 2560x1440 resolution camera's

### ISSUE THREAD

**Issue by ukstorm** [IPCams/BugTracker#55]
First thank you for a wonderful app and bringing it to MacOS I love the fact I can sync it across all my devices! I've found a bug that the MacOS version won't display camera's with a resolution of 2560x1440. It's fine with a HD resolution of the same make SV3C. iPhone, iPad & Apple TV show the camera's fine. All on the latest version of you software 2.3.2
MacBook Pro (Big Sur 11.2.3 )
Using RTSP

Keep up the good work
James

**Comment by tylerjonesio** [comment]
Thanks for your support and the detailed bug report! Do you happen to know if your 1440p camera is using an h265 stream? I've identified an issue in #56 where there was an odd compatibility problem with h265 streams, which should be resolved with IPCams version 2.3.3 which is currently rolling out via the app store. Feel free to try out the new version and see if it fixes things for you. But if not, I can keep digging to see what else might be amiss.

**Comment by ukstorm** [comment]
Yes the ones that didn't work are h265 streams, 2.3.3 broke everything (wheel on h265/h264 camera's) 2.3.4 sorted it. Thank you again for a great app!

James
