### ISSUE TITLE
Big Sur 11.2.3 No video, only audio. Same settings (through iCloud sync) on iOS work.

### ISSUE THREAD

**Issue by Tezzlicious** [IPCams/BugTracker#56]
**Describe the bug**
On the desktop app my Imou camera streams don't show the video. Audio is audible during playback.

**To Reproduce**

Add imou IPC-F22A through the following RTSP URL:

<IP>
Port: 554
Path: /live

HTTP Auth enabled: admin/camera pass is shown on device label in the about section

Press on the camera and it opens the stream. Only audio is audible. No video.

**Expected behavior**
Video and Audio work.

**Screenshots**
[https://www.tezzi.com/ipcams.png](url)

**App Version**
Version 2.3.2 (8)

**Device & OS Version**
Big Sur 11.2.3 
Same settings work on several iPhones with iOS 14.3.

**Additional context**

**Comment by tylerjonesio** [comment]
Thanks for the detailed bug report! After a quick google it looks like your camera supports an h265 stream, which I think might have been part of the issue. I was at least able to reproduce an h265 issue on my end with one of my cameras (which defaults to h264 and is why I didn't catch it originally) where the video stream was missing but audio worked. 

The good news is that I think I've fixed this bug in version 2.3.3 which is currently rolling our via the App Store. Feel free to try it out and let me know how it works for you. Hopefully this resolves the issue! But if not, I can keep digging.

**Comment by Tezzlicious** [comment]
Hi! Version 2.3.3 (11) fixed it. All my cams are working now. Thanks for this wonderful piece of software. My favourite app for IP cams.
