### ISSUE TITLE
Ability to disable audio on RTSP feed

### ISSUE THREAD

**Issue by fmarcoux96** [IPCams/BugTracker#6]
**Is your feature request related to a problem? Please describe.**
I am using the new Grandstream SIP Cameras and they support audio through an external mic/speaker jack. Unfortunately, since I am not using that, there's always a small background noise in the audio feed from the camera, which I can hear in the app (and bugs a bit on the Dashboard because of multiple cameras).

**Describe the solution you'd like**
I'd like to have an option, under each camera, to disable the audio feed (probably only works for RTSP but can be useful for other types).

**Additional context**
Nothing else to add I believe.

**Comment by tylerjonesio** [comment]
Thanks for the request! I'm working on something for this and hope to have it out in a major release sometime soon.

**Comment by fmarcoux96** [comment]
I saw the recent update which has that ability. However, even when disabled on the camera settings, the audio is on when you open it. I have to manually press mute.

**Comment by tylerjonesio** [comment]
Can you verify that the 'Disable Audio Stream' setting when editing your camera is saving properly? If that settings is toggled on, the mute button should be hidden from the camera view as there wouldn't be any audio stream to mute.

**Comment by fmarcoux96** [comment]
> Can you verify that the 'Disable Audio Stream' setting when editing your camera is saving properly? If that settings is toggled on, the mute button should be hidden from the camera view as there wouldn't be any audio stream to mute.

You are right. For some reason, it wasn't saved the first time I configured it. I redid the setting and now the mute button is hidden. Thanks!

**Comment by tylerjonesio** [comment]
Awesome! I'm glad that it is working. If any other issues arise with it, feel free to file a bug report.
