### ISSUE TITLE
Easy way to switch cameras

### ISSUE THREAD

**Issue by fmarcoux96** [IPCams/BugTracker#7]
**Is your feature request related to a problem? Please describe.**
When I check my cams, it's a bit annoying of always having to do Back to change cameras (just because the animation is slow).

**Describe the solution you'd like**
Could we have a small menu, in the camera view, to switch cams? Something like a popover when we tap the cam name.

**Additional context**
Either a popover, a menu, or simply and Next/Prev Cam buttons, with arrows. That could be great too to cycle through them.

**Comment by tylerjonesio** [comment]
Thanks for the request, I love the idea! I'll look into this and see what I can do.

**Comment by Gigster527** [comment]
For iPhones, swipe left or right to cycle between cameras. That would be awesome, agree with OP cumbersome to go back and select different camera to change the view.

**Comment by tylerjonesio** [comment]
Good news! IPCams 2.2 is in the process of rolling out and includes a menu in the camera view to easily switch cameras. You can access it by tapping the camera name in the navigation bar. Feel free to leave a bug report for any issues that arise.
