### ISSUE TITLE
Apple TV App

### ISSUE THREAD

**Issue by fmarcoux96** [IPCams/BugTracker#8]
**Is your feature request related to a problem? Please describe.**
No problem, just it'd be freaking cool.

**Describe the solution you'd like**
Have a simple Apple TV app that can show the dashboard and maybe cycle through multiple pages of 4 cams, on a programmed interval. This way, it could be use as monitoring.

**Additional context**
Of course, any Smart TV apps could be awesome. AirPlay Mirroring sucks and needs a device always on. The Apple TV is already made for this. (With the new UI, it would be slick!)

**Comment by tylerjonesio** [comment]
Thanks for the request! I agree that having an Apple TV app would be awesome. I'm currently working on one, but not sure when it'll be ready. I'm hoping sometime later this fall or early next year.

**Comment by tylerjonesio** [comment]
Great news! IPCams 2.2 is out and includes a new Apple TV app. Feel free to leave a bug report for any issues that arise or file a feature request for any improvement suggestions.
