### ISSUE TITLE
Open dashboard as default when opening the app

### ISSUE THREAD

**Issue by shinji666** [IPCams/BugTracker#9]
**Is your feature request related to a problem? Please describe.**
Default to dashboard full screen when opening the app instead of camera list

**Describe the solution you'd like**
Change the default view, once camera setting is configured, rarely need to change it. Most common use case is to open the app to view the dashboard (awesome if can select which dashboard as default!)

**Additional context**

**Comment by tylerjonesio** [comment]
Thanks for the request! I'll look to see what I can do to have the default page configurable. 

In the mean time, you can kind of achieve a similar goal by setting up and launching the app via the app shortcuts (long press on app icon). You can setup a shortcut to open the dashboard directly on launch.

**Comment by shinji666** [comment]
Thanks! I’ve been doing that for now :)

**Comment by tylerjonesio** [comment]
Good news! IPCams 2.2 is in the process of rolling out and includes the ability to customize the default launch view of the app. In the settings tab and you'll find the `Launch Shortcut` option which has the ability to choose a camera or dashboard as the default launch screen. Feel free to leave a bug report for any issues that arise.
